package cc

import (
	mime "github.com/vault-thirteen/auxie/MIME"
)

const (
	Asset_IndexHtml  = "index.html"
	Asset_MainJs     = "main.js"
	Asset_ApiJs      = "api.js"
	Asset_ModelsJs   = "models.js"
	Asset_UiJs       = "ui.js"
	Asset_StylesCss  = "styles.css"
	Asset_FaviconPng = "favicon.png"

	// Virtual assets generated by server.

	Asset_SettingsJson        = "settings.json"
	Asset_FrontEndVersionJson = "frontend-version.json"
)

const (
	ContentType_Html = mime.TypeTextHtml + "; charset=utf-8"
)
